name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "lib/**"
      - "web/**"
      - "pubspec.yaml"
      - "analysis_options.yaml"
      - "data/draws.json"
      - ".github/workflows/deploy_pages.yml"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (PWA)
        run: |
          flutter build web --release \
            --pwa-strategy=offline-first \
            --base-href "/bingo-hot/"

      # ⭐ 把最新 draws.json 放到發佈資料夾
      - name: Copy latest draws.json into build
        run: |
          mkdir -p build/web/data
          cp -f data/draws.json build/web/data/draws.json
          ls -lah build/web/data

      - name: Deploy to GitHub Pages (push to gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          # 若你之後想保留 gh-pages 其他手動上傳的檔案，可設 keep_files: true
          # keep_files: false