name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 需要寫入權限推到 gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (PWA)
        run: |
          flutter build web --release \
            --pwa-strategy=offline-first \
            --base-href "/bingo-hot/"

      # ⭐ 關鍵：把最新的 draws.json 放到發佈資料夾（在 build 之後做）
      - name: Copy draws.json
        run: |
          mkdir -p build/web/data
          cp -f data/draws.json build/web/data/draws.json
          ls -lah build/web/data

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
