name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

# ✅ 關鍵：讓 GITHUB_TOKEN 具有寫入權限，才能推 gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (PWA)
        run: |
          flutter build web --release \
            --pwa-strategy=offline-first \
            --base-href "/bingo-hot/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
